CREATE TABLE IF NOT EXISTS `transactions` (
	`id` BIGINT(19) NOT NULL AUTO_INCREMENT,
	`account_number` VARCHAR(255) NULL DEFAULT NULL COLLATE 'latin1_bin',
	`customer_id` VARCHAR(255) NULL DEFAULT NULL COLLATE 'latin1_bin',
	`description` VARCHAR(255) NULL DEFAULT NULL COLLATE 'latin1_bin',
	`trx_amount` DECIMAL(38,2) NULL DEFAULT NULL,
	`trx_date` DATE NULL DEFAULT NULL,
	`trx_time` TIME(6) NULL DEFAULT NULL,
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='latin1_bin'
ENGINE=InnoDB
;

CREATE TABLE IF NOT EXISTS `user` (
	`id` BIGINT(19) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(255) NULL DEFAULT NULL COLLATE 'latin1_bin',
	`password` VARCHAR(255) NULL DEFAULT NULL COLLATE 'latin1_bin',
	`roles` VARCHAR(255) NULL DEFAULT NULL COLLATE 'latin1_bin',
	`username` VARCHAR(255) NULL DEFAULT NULL COLLATE 'latin1_bin',
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='latin1_bin'
ENGINE=InnoDB
;